#!/bin/bash
declare -A seen_dirs find . -type f-iname "*.git"|while read -r f do dir="${f%/*}" name="${f##*/}" base_name=${name%.gif} if[-z"${seen_dirs[$dir]}"then seen_dirs[$dir]=1 print"%s\n" "$base_name" fi done|sort -f
