#!/bin/bash
seen_dirs=() find . -type f -iname "*.gif" | while IFS= read -r f do dir="${f%/*}" name="${f##*/}" base_name="${name%.gif}" if [[ ! " ${seen_dirs[*]} " =~ " $dir " ]] then seen_dirs+=("$dir") printf "%s\n" "$base_name" fi done | sort -f
